### ISSUE TITLE
How to delaying to SubMenu affect?

### ISSUE THREAD

**Issue by ibradura** [TemplatemonsterPlugins/rd-navbar#11]
I getting pages of menu from database by ajax get method. So pages data of menu are a little late loading but your about menu scripts already loaded. So my primary pages looks nice but sub pages looks opened while that should be open on primary pages hover. Have a solution for this?

**Comment by TmHtmlDept** [comment]
Hi. You need just initialize rd-navbar after you get ajax driven data (in callback)

Ex.
$.ajax({
  method: "POST",
  url: "some.php",
  data: { name: "John", location: "Smith" }
})
  .done(function( msg ) {
    // Init rd-navbar here
    //...
  });

Reply me if it is fine for you.

**Comment by ibradura** [comment]
It works now. Thank you so much for your advice. I did like you said: rd-navbar init part in script.js moves to after get ajax data.
