### ISSUE TITLE
touch enabled displays

### ISSUE THREAD

**Issue by a-hulman** [TemplatemonsterPlugins/rd-navbar#12]
Hello,
it seems that navbar is not working "right" on touch-enabled desktops. On a notebook screen that is touch enabled a tablet version will display and mouse cannot be used. Happens on many layouts, downloaded one
http://jokertaxi.sk/

Any ideas?

**Comment by OXAYAZA** [comment]
You can use the `deviceLayout` parameter with a specific resolution:
```js
$('#navbar').RDNavbar({
	responsive: {
		992: {
			deviceLayout: 'rd-navbar-static',
			layout: 'rd-navbar-static'
		}
	}
});

```
