### ISSUE TITLE
What is the last version?

### ISSUE THREAD

**Issue by kelp404** [TemplatemonsterPlugins/rd-navbar#15]
http://cms.devoffice.com/coding-dev/rd-navbar/documentation/
```
04/25/2016 Version 2.1.5. The classes for submenus are added in case they do not fit in the screen. The data-rd-navbar-toggle attribute now searches for elements in the body context, not in rd-navbar.
```

https://github.com/ZemezPlugins/rd-navbar/blob/master/dist/css/rd-navbar.css#L9
```css
/*
* @subsection   RD Navbar
*
* @description  Describes style declarations for RD Navbar extension
*
* @author       Evgeniy Gusarov
* @link         https://ua.linkedin.com/pub/evgeniy-gusarov/8a/a40/54a
* @version      2.1.6
*/
```

https://github.com/ZemezPlugins/rd-navbar/blob/master/dist/js/jquery.rd-navbar.js#L5
```js
/**
 * @module       RD Navbar
 * @author       Evgeniy Gusarov
 * @see          https://ua.linkedin.com/pub/evgeniy-gusarov/8a/a40/54a
 * @version      2.2.5
 */
```

2.1.5, 2.1.6, 2.2.5 ???

![e99e6b5e-ca6c-4c19-87b7-dfd63db6381a_m](https://user-images.githubusercontent.com/1680868/41506149-b76b48b6-724a-11e8-949a-9eada29cf1b1.jpg)

Could you add a tag? PLEASE!!

**Comment by OXAYAZA** [comment]
[2.2.5 - Current version](https://github.com/ZemezPlugins/rd-navbar/releases/tag/2.2.5)
