### ISSUE TITLE
Expand dropdown on menu item

### ISSUE THREAD

**Issue by Foundas** [TemplatemonsterPlugins/rd-navbar#4]
Hi,
when on mobile/tablets, if menu item has drop-down, it is shown as an arrow and user clicks it to expand/show dropdown. Is there a way to expand/show this dropdown when user clicks the menu title and not just the arrow icon?

Thanks in advance

**Comment by nbashev** [comment]
Is there any solution for this feature ?

**Comment by temilson** [comment]
Yes, is there a solution for this?
https://www.screencast.com/t/DFfTwfQNWW

**Comment by OXAYAZA** [comment]
This solution is not advisable on mobile devices. If a user needs to follow a link or open a submenu, he does it without unnecessary clicks. It is also necessary to close the submenu without closing the main menu in mobile layout.

**Comment by mkysoft** [comment]
You get this functionality with below changes @temilson 

Insert below line to js file after 607.
> $this.find('> .rd-nav-link').on('click', $.proxy(ctx.dropdownToggle, this, ctx));
Replace item href value with "#".
