### ISSUE TITLE
English docs?

### ISSUE THREAD

**Issue by DanyHenriquez** [TemplatemonsterPlugins/rd-navbar#6]
Can someone make proper english documentation?

**Comment by nicoepp** [comment]
English docs would be very appreciated!

**Comment by Mnemon1k** [comment]
Here is [english doc](https://www.templatemonster.com/help/quick-start-guide/website-templates/v1-3/index.php?lang=en&section=extensions#rd-navbar)

**Comment by nicoepp** [comment]
Using Google you cannot find this documentation for the newest version and the Readme of this project does only link to the russian documentation.
